//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package offloads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/weaviate/weaviate/entities/models"
)

// OffloadHandlerFunc turns a function with the right signature into a offload handler
type OffloadHandlerFunc func(OffloadParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn OffloadHandlerFunc) Handle(params OffloadParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// OffloadHandler interface for that can handle valid offload params
type OffloadHandler interface {
	Handle(OffloadParams, *models.Principal) middleware.Responder
}

// NewOffload creates a new http.Handler for the offload operation
func NewOffload(ctx *middleware.Context, handler OffloadHandler) *Offload {
	return &Offload{Context: ctx, Handler: handler}
}

/*
	Offload swagger:route POST /offloads/{backend}/{class} offloads offload

Starts a process of creating an offload for a set of tenants
*/
type Offload struct {
	Context *middleware.Context
	Handler OffloadHandler
}

func (o *Offload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewOffloadParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
