//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShardMovement shard movement
//
// swagger:model ShardMovement
type ShardMovement struct {

	// node ID to move replica from
	FromNode string `json:"fromNode,omitempty"`

	// name of the shard...id?
	ShardName string `json:"shardName,omitempty"`

	// node ID to move replica to
	ToNode string `json:"toNode,omitempty"`
}

// Validate validates this shard movement
func (m *ShardMovement) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this shard movement based on context it is used
func (m *ShardMovement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ShardMovement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShardMovement) UnmarshalBinary(b []byte) error {
	var res ShardMovement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
