//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package shardmovements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// ShardmovementsCreateReader is a Reader for the ShardmovementsCreate structure.
type ShardmovementsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShardmovementsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShardmovementsCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShardmovementsCreateOK creates a ShardmovementsCreateOK with default headers values
func NewShardmovementsCreateOK() *ShardmovementsCreateOK {
	return &ShardmovementsCreateOK{}
}

/*
ShardmovementsCreateOK describes a response with status code 200, with default header values.

ShardMovement created.
*/
type ShardmovementsCreateOK struct {
	Payload *models.ShardMovement
}

// IsSuccess returns true when this shardmovements create o k response has a 2xx status code
func (o *ShardmovementsCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this shardmovements create o k response has a 3xx status code
func (o *ShardmovementsCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this shardmovements create o k response has a 4xx status code
func (o *ShardmovementsCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this shardmovements create o k response has a 5xx status code
func (o *ShardmovementsCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this shardmovements create o k response a status code equal to that given
func (o *ShardmovementsCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the shardmovements create o k response
func (o *ShardmovementsCreateOK) Code() int {
	return 200
}

func (o *ShardmovementsCreateOK) Error() string {
	return fmt.Sprintf("[POST /shardmovements][%d] shardmovementsCreateOK  %+v", 200, o.Payload)
}

func (o *ShardmovementsCreateOK) String() string {
	return fmt.Sprintf("[POST /shardmovements][%d] shardmovementsCreateOK  %+v", 200, o.Payload)
}

func (o *ShardmovementsCreateOK) GetPayload() *models.ShardMovement {
	return o.Payload
}

func (o *ShardmovementsCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ShardMovement)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
