//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package shardmovements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// NewShardmovementsCreateParams creates a new ShardmovementsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShardmovementsCreateParams() *ShardmovementsCreateParams {
	return &ShardmovementsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewShardmovementsCreateParamsWithTimeout creates a new ShardmovementsCreateParams object
// with the ability to set a timeout on a request.
func NewShardmovementsCreateParamsWithTimeout(timeout time.Duration) *ShardmovementsCreateParams {
	return &ShardmovementsCreateParams{
		timeout: timeout,
	}
}

// NewShardmovementsCreateParamsWithContext creates a new ShardmovementsCreateParams object
// with the ability to set a context for a request.
func NewShardmovementsCreateParamsWithContext(ctx context.Context) *ShardmovementsCreateParams {
	return &ShardmovementsCreateParams{
		Context: ctx,
	}
}

// NewShardmovementsCreateParamsWithHTTPClient creates a new ShardmovementsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewShardmovementsCreateParamsWithHTTPClient(client *http.Client) *ShardmovementsCreateParams {
	return &ShardmovementsCreateParams{
		HTTPClient: client,
	}
}

/*
ShardmovementsCreateParams contains all the parameters to send to the API endpoint

	for the shardmovements create operation.

	Typically these are written to a http.Request.
*/
type ShardmovementsCreateParams struct {

	// Body.
	Body *models.ShardMovement

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the shardmovements create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShardmovementsCreateParams) WithDefaults() *ShardmovementsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the shardmovements create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShardmovementsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the shardmovements create params
func (o *ShardmovementsCreateParams) WithTimeout(timeout time.Duration) *ShardmovementsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the shardmovements create params
func (o *ShardmovementsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the shardmovements create params
func (o *ShardmovementsCreateParams) WithContext(ctx context.Context) *ShardmovementsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the shardmovements create params
func (o *ShardmovementsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the shardmovements create params
func (o *ShardmovementsCreateParams) WithHTTPClient(client *http.Client) *ShardmovementsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the shardmovements create params
func (o *ShardmovementsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the shardmovements create params
func (o *ShardmovementsCreateParams) WithBody(body *models.ShardMovement) *ShardmovementsCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the shardmovements create params
func (o *ShardmovementsCreateParams) SetBody(body *models.ShardMovement) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ShardmovementsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
