//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package offloads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new offloads API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for offloads API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Offload(params *OffloadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OffloadOK, error)

	Onload(params *OnloadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OnloadOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
Offload Starts a process of creating an offload for a set of tenants
*/
func (a *Client) Offload(params *OffloadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OffloadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOffloadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "offload",
		Method:             "POST",
		PathPattern:        "/offloads/{backend}/{class}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "application/yaml"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OffloadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OffloadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for offload: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
Onload Starts a process of onloading a set of tenants
*/
func (a *Client) Onload(params *OnloadParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*OnloadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOnloadParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "onload",
		Method:             "POST",
		PathPattern:        "/offloads/{backend}/{class}/onload",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "application/yaml"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OnloadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OnloadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for onload: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
