//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package offloads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate/entities/models"
)

// NewOnloadParams creates a new OnloadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOnloadParams() *OnloadParams {
	return &OnloadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOnloadParamsWithTimeout creates a new OnloadParams object
// with the ability to set a timeout on a request.
func NewOnloadParamsWithTimeout(timeout time.Duration) *OnloadParams {
	return &OnloadParams{
		timeout: timeout,
	}
}

// NewOnloadParamsWithContext creates a new OnloadParams object
// with the ability to set a context for a request.
func NewOnloadParamsWithContext(ctx context.Context) *OnloadParams {
	return &OnloadParams{
		Context: ctx,
	}
}

// NewOnloadParamsWithHTTPClient creates a new OnloadParams object
// with the ability to set a custom HTTPClient for a request.
func NewOnloadParamsWithHTTPClient(client *http.Client) *OnloadParams {
	return &OnloadParams{
		HTTPClient: client,
	}
}

/*
OnloadParams contains all the parameters to send to the API endpoint

	for the onload operation.

	Typically these are written to a http.Request.
*/
type OnloadParams struct {

	/* Backend.

	   Backup backend name e.g. filesystem, gcs, s3.
	*/
	Backend string

	// Body.
	Body *models.OnloadRequest

	/* Class.

	   Class (name) offloaded tenants belong to
	*/
	Class string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the onload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OnloadParams) WithDefaults() *OnloadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the onload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OnloadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the onload params
func (o *OnloadParams) WithTimeout(timeout time.Duration) *OnloadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the onload params
func (o *OnloadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the onload params
func (o *OnloadParams) WithContext(ctx context.Context) *OnloadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the onload params
func (o *OnloadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the onload params
func (o *OnloadParams) WithHTTPClient(client *http.Client) *OnloadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the onload params
func (o *OnloadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackend adds the backend to the onload params
func (o *OnloadParams) WithBackend(backend string) *OnloadParams {
	o.SetBackend(backend)
	return o
}

// SetBackend adds the backend to the onload params
func (o *OnloadParams) SetBackend(backend string) {
	o.Backend = backend
}

// WithBody adds the body to the onload params
func (o *OnloadParams) WithBody(body *models.OnloadRequest) *OnloadParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the onload params
func (o *OnloadParams) SetBody(body *models.OnloadRequest) {
	o.Body = body
}

// WithClass adds the class to the onload params
func (o *OnloadParams) WithClass(class string) *OnloadParams {
	o.SetClass(class)
	return o
}

// SetClass adds the class to the onload params
func (o *OnloadParams) SetClass(class string) {
	o.Class = class
}

// WriteToRequest writes these params to a swagger request
func (o *OnloadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param backend
	if err := r.SetPathParam("backend", o.Backend); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param class
	if err := r.SetPathParam("class", o.Class); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
