//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package shardmovements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/weaviate/weaviate/entities/models"
)

// ShardmovementsCreateOKCode is the HTTP code returned for type ShardmovementsCreateOK
const ShardmovementsCreateOKCode int = 200

/*
ShardmovementsCreateOK ShardMovement created.

swagger:response shardmovementsCreateOK
*/
type ShardmovementsCreateOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShardMovement `json:"body,omitempty"`
}

// NewShardmovementsCreateOK creates ShardmovementsCreateOK with default headers values
func NewShardmovementsCreateOK() *ShardmovementsCreateOK {

	return &ShardmovementsCreateOK{}
}

// WithPayload adds the payload to the shardmovements create o k response
func (o *ShardmovementsCreateOK) WithPayload(payload *models.ShardMovement) *ShardmovementsCreateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shardmovements create o k response
func (o *ShardmovementsCreateOK) SetPayload(payload *models.ShardMovement) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShardmovementsCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
